[tool.poetry]
name="AI Lab"
description="Lab of the lecture 'Artificial Intelligence' at my university"
authors = ["Felix Schneider <mail@fschneider.me>"]
version = "0.1"
package-mode = false

[tool.poetry.dependencies]
python = "3.11"
torch = "^2.4.1"
numpy = "^2.1.1"
